//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Configuration_Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bank_Configuration_Portal.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions_Label {
            get {
                return ResourceManager.GetString("Actions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active_Label {
            get {
                return ResourceManager.GetString("Active_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Configuration Portal.
        /// </summary>
        public static string Application_Label {
            get {
                return ResourceManager.GetString("Application_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch has been modified by another user.
        /// </summary>
        public static string Branch_Concurrency_Error {
            get {
                return ResourceManager.GetString("Branch_Concurrency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Branch.
        /// </summary>
        public static string Branch_Create_Button {
            get {
                return ResourceManager.GetString("Branch_Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch.
        /// </summary>
        public static string Branch_Create_Title {
            get {
                return ResourceManager.GetString("Branch_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch created successfully..
        /// </summary>
        public static string Branch_Created_Successfully {
            get {
                return ResourceManager.GetString("Branch_Created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch deleted successfully..
        /// </summary>
        public static string Branch_Deleted_Successfully {
            get {
                return ResourceManager.GetString("Branch_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Branch.
        /// </summary>
        public static string Branch_Edit_Title {
            get {
                return ResourceManager.GetString("Branch_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branch_Index_Title {
            get {
                return ResourceManager.GetString("Branch_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Branch_IsActive {
            get {
                return ResourceManager.GetString("Branch_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter branch name.
        /// </summary>
        public static string Branch_Name_Placeholder {
            get {
                return ResourceManager.GetString("Branch_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Arabic characters allowed.
        /// </summary>
        public static string Branch_NameArabic_Invalid {
            get {
                return ResourceManager.GetString("Branch_NameArabic_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        public static string Branch_NameArabic_Label {
            get {
                return ResourceManager.GetString("Branch_NameArabic_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name (Arabic) has a max limit of a (100) characters.
        /// </summary>
        public static string Branch_NameArabic_MaxLimit {
            get {
                return ResourceManager.GetString("Branch_NameArabic_MaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter branch name (AR).
        /// </summary>
        public static string Branch_NameArabic_Placeholder {
            get {
                return ResourceManager.GetString("Branch_NameArabic_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic) is required.
        /// </summary>
        public static string Branch_NameArabic_Required {
            get {
                return ResourceManager.GetString("Branch_NameArabic_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only English characters allowed.
        /// </summary>
        public static string Branch_NameEnglish_Invalid {
            get {
                return ResourceManager.GetString("Branch_NameEnglish_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string Branch_NameEnglish_Label {
            get {
                return ResourceManager.GetString("Branch_NameEnglish_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name (English) has a max limit of a (100) characters.
        /// </summary>
        public static string Branch_NameEnglish_MaxLimit {
            get {
                return ResourceManager.GetString("Branch_NameEnglish_MaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter branch name (EN).
        /// </summary>
        public static string Branch_NameEnglish_Placeholder {
            get {
                return ResourceManager.GetString("Branch_NameEnglish_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English) is required.
        /// </summary>
        public static string Branch_NameEnglish_Required {
            get {
                return ResourceManager.GetString("Branch_NameEnglish_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch not found..
        /// </summary>
        public static string Branch_Not_Found {
            get {
                return ResourceManager.GetString("Branch_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Branch_Update_Button {
            get {
                return ResourceManager.GetString("Branch_Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch updated successfully..
        /// </summary>
        public static string Branch_Updated_Successfully {
            get {
                return ResourceManager.GetString("Branch_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches_Title {
            get {
                return ResourceManager.GetString("Branches_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this branch?.
        /// </summary>
        public static string ConfirmDelete_Message {
            get {
                return ResourceManager.GetString("ConfirmDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Label {
            get {
                return ResourceManager.GetString("Delete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Label {
            get {
                return ResourceManager.GetString("Edit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again.
        /// </summary>
        public static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive_Label {
            get {
                return ResourceManager.GetString("Inactive_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string IsActive_Label {
            get {
                return ResourceManager.GetString("IsActive_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string Login_BankName_Label {
            get {
                return ResourceManager.GetString("Login_BankName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter bank name.
        /// </summary>
        public static string Login_BankName_Placeholder {
            get {
                return ResourceManager.GetString("Login_BankName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name is required.
        /// </summary>
        public static string Login_BankName_Required {
            get {
                return ResourceManager.GetString("Login_BankName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank not found..
        /// </summary>
        public static string Login_Error_NoBank {
            get {
                return ResourceManager.GetString("Login_Error_NoBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bank name..
        /// </summary>
        public static string Login_Invalid_Bank {
            get {
                return ResourceManager.GetString("Login_Invalid_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist or is not authorized for this bank.
        /// </summary>
        public static string Login_Unauthorized_User {
            get {
                return ResourceManager.GetString("Login_Unauthorized_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_UserName_Label {
            get {
                return ResourceManager.GetString("Login_UserName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username .
        /// </summary>
        public static string Login_UserName_Placeholder {
            get {
                return ResourceManager.GetString("Login_UserName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string Login_UserName_Required {
            get {
                return ResourceManager.GetString("Login_UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Logout_Button {
            get {
                return ResourceManager.GetString("Logout_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string Logout_Confirm_Message {
            get {
                return ResourceManager.GetString("Logout_Confirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Logout.
        /// </summary>
        public static string Logout_Confirm_Title {
            get {
                return ResourceManager.GetString("Logout_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
    }
}
