//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Configuration_Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bank_Configuration_Portal.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions_Label {
            get {
                return ResourceManager.GetString("Actions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active_Label {
            get {
                return ResourceManager.GetString("Active_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Services.
        /// </summary>
        public static string Active_Service_Index_Title {
            get {
                return ResourceManager.GetString("Active_Service_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Configuration Portal.
        /// </summary>
        public static string Application_Label {
            get {
                return ResourceManager.GetString("Application_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to branches.
        /// </summary>
        public static string Back_To_Branches_Button {
            get {
                return ResourceManager.GetString("Back_To_Branches_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Bank.
        /// </summary>
        public static string Bank_Arab_Bank {
            get {
                return ResourceManager.GetString("Bank_Arab Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch already deleted by another user (Refreshing changes).
        /// </summary>
        public static string Branch_Already_Deleted {
            get {
                return ResourceManager.GetString("Branch_Already_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch has been modified by another user.
        /// </summary>
        public static string Branch_Concurrency_Error {
            get {
                return ResourceManager.GetString("Branch_Concurrency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Branch.
        /// </summary>
        public static string Branch_Create_Button {
            get {
                return ResourceManager.GetString("Branch_Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch.
        /// </summary>
        public static string Branch_Create_Title {
            get {
                return ResourceManager.GetString("Branch_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch created successfully..
        /// </summary>
        public static string Branch_Created_Successfully {
            get {
                return ResourceManager.GetString("Branch_Created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch has been modified by another user. Are you sure you want to delete it?.
        /// </summary>
        public static string Branch_Delete_Concurrency_Error {
            get {
                return ResourceManager.GetString("Branch_Delete_Concurrency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch deleted successfully..
        /// </summary>
        public static string Branch_Deleted_Successfully {
            get {
                return ResourceManager.GetString("Branch_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Branch.
        /// </summary>
        public static string Branch_Edit_Title {
            get {
                return ResourceManager.GetString("Branch_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branch_Index_Title {
            get {
                return ResourceManager.GetString("Branch_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Branch_IsActive {
            get {
                return ResourceManager.GetString("Branch_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter branch name.
        /// </summary>
        public static string Branch_Name_Placeholder {
            get {
                return ResourceManager.GetString("Branch_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter branch name (AR).
        /// </summary>
        public static string Branch_NameArabic_Placeholder {
            get {
                return ResourceManager.GetString("Branch_NameArabic_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter branch name (EN).
        /// </summary>
        public static string Branch_NameEnglish_Placeholder {
            get {
                return ResourceManager.GetString("Branch_NameEnglish_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes detected to branch.
        /// </summary>
        public static string Branch_NoChangesDetected {
            get {
                return ResourceManager.GetString("Branch_NoChangesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch not found..
        /// </summary>
        public static string Branch_Not_Found {
            get {
                return ResourceManager.GetString("Branch_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch updated successfully..
        /// </summary>
        public static string Branch_Updated_Successfully {
            get {
                return ResourceManager.GetString("Branch_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches_Title {
            get {
                return ResourceManager.GetString("Branches_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string ChangePassword_Button {
            get {
                return ResourceManager.GetString("ChangePassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ChangePassword_Confirm_Label {
            get {
                return ResourceManager.GetString("ChangePassword_Confirm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter the new password.
        /// </summary>
        public static string ChangePassword_Confirm_Placeholder {
            get {
                return ResourceManager.GetString("ChangePassword_Confirm_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the new password..
        /// </summary>
        public static string ChangePassword_Confirm_Required {
            get {
                return ResourceManager.GetString("ChangePassword_Confirm_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password you entered is incorrect..
        /// </summary>
        public static string ChangePassword_InvalidOldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePassword_New_Label {
            get {
                return ResourceManager.GetString("ChangePassword_New_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password.
        /// </summary>
        public static string ChangePassword_New_Placeholder {
            get {
                return ResourceManager.GetString("ChangePassword_New_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        public static string ChangePassword_New_Required {
            get {
                return ResourceManager.GetString("ChangePassword_New_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string ChangePassword_Old_Label {
            get {
                return ResourceManager.GetString("ChangePassword_Old_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.
        /// </summary>
        public static string ChangePassword_Old_Placeholder {
            get {
                return ResourceManager.GetString("ChangePassword_Old_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required..
        /// </summary>
        public static string ChangePassword_Old_Required {
            get {
                return ResourceManager.GetString("ChangePassword_Old_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change your password to continue..
        /// </summary>
        public static string ChangePassword_Required_Note {
            get {
                return ResourceManager.GetString("ChangePassword_Required_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear_Button {
            get {
                return ResourceManager.GetString("Clear_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency Conflict.
        /// </summary>
        public static string Concurrency_Conflict_Title {
            get {
                return ResourceManager.GetString("Concurrency_Conflict_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent update failed.
        /// </summary>
        public static string Concurrency_ForceFailed {
            get {
                return ResourceManager.GetString("Concurrency_ForceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to enforce your changes.
        /// </summary>
        public static string Concurrency_ForcePrompt {
            get {
                return ResourceManager.GetString("Concurrency_ForcePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string ConfirmDelete_Message {
            get {
                return ResourceManager.GetString("ConfirmDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter already deleted by another user (Refreshing changes).
        /// </summary>
        public static string Counter_Already_Deleted {
            get {
                return ResourceManager.GetString("Counter_Already_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Counter has been modified by another user.
        /// </summary>
        public static string Counter_Concurrency_Error {
            get {
                return ResourceManager.GetString("Counter_Concurrency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Counter.
        /// </summary>
        public static string Counter_Create_Button {
            get {
                return ResourceManager.GetString("Counter_Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Counter.
        /// </summary>
        public static string Counter_Create_Title {
            get {
                return ResourceManager.GetString("Counter_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Created Successfully.
        /// </summary>
        public static string Counter_Created_Successfully {
            get {
                return ResourceManager.GetString("Counter_Created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Counter has been modified by another user, Are you sure you want to delete it?.
        /// </summary>
        public static string Counter_Delete_Concurrency_Error {
            get {
                return ResourceManager.GetString("Counter_Delete_Concurrency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Deleted Successfully.
        /// </summary>
        public static string Counter_Deleted_Successfully {
            get {
                return ResourceManager.GetString("Counter_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Counter.
        /// </summary>
        public static string Counter_Edit_Title {
            get {
                return ResourceManager.GetString("Counter_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        public static string Counter_Index_Title {
            get {
                return ResourceManager.GetString("Counter_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Counter name (AR).
        /// </summary>
        public static string Counter_NameArabic_Placeholder {
            get {
                return ResourceManager.GetString("Counter_NameArabic_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Counter name (EN).
        /// </summary>
        public static string Counter_NameEnglish_Placeholder {
            get {
                return ResourceManager.GetString("Counter_NameEnglish_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes detected to Counter.
        /// </summary>
        public static string Counter_NoChangesDetected {
            get {
                return ResourceManager.GetString("Counter_NoChangesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter not found..
        /// </summary>
        public static string Counter_Not_Found {
            get {
                return ResourceManager.GetString("Counter_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Type.
        /// </summary>
        public static string Counter_Type_Label {
            get {
                return ResourceManager.GetString("Counter_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Updated Successfully.
        /// </summary>
        public static string Counter_Updated_Successfully {
            get {
                return ResourceManager.GetString("Counter_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        public static string CounterType_CustomerService {
            get {
                return ResourceManager.GetString("CounterType_CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teller.
        /// </summary>
        public static string CounterType_Teller {
            get {
                return ResourceManager.GetString("CounterType_Teller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Label {
            get {
                return ResourceManager.GetString("Delete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Label {
            get {
                return ResourceManager.GetString("Edit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Save.
        /// </summary>
        public static string Force_Save {
            get {
                return ResourceManager.GetString("Force_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again.
        /// </summary>
        public static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive_Label {
            get {
                return ResourceManager.GetString("Inactive_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string IsActive_Label {
            get {
                return ResourceManager.GetString("IsActive_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string Login_BankName_Label {
            get {
                return ResourceManager.GetString("Login_BankName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter bank name.
        /// </summary>
        public static string Login_BankName_Placeholder {
            get {
                return ResourceManager.GetString("Login_BankName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name is required.
        /// </summary>
        public static string Login_BankName_Required {
            get {
                return ResourceManager.GetString("Login_BankName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank not found..
        /// </summary>
        public static string Login_Error_NoBank {
            get {
                return ResourceManager.GetString("Login_Error_NoBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bank name..
        /// </summary>
        public static string Login_Invalid_Bank {
            get {
                return ResourceManager.GetString("Login_Invalid_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string Login_Invalid_Credentials {
            get {
                return ResourceManager.GetString("Login_Invalid_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password_Label {
            get {
                return ResourceManager.GetString("Login_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Login_Password_Placeholder {
            get {
                return ResourceManager.GetString("Login_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Login_Password_Required {
            get {
                return ResourceManager.GetString("Login_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist or is not authorized for this bank.
        /// </summary>
        public static string Login_Unauthorized_User {
            get {
                return ResourceManager.GetString("Login_Unauthorized_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_UserName_Label {
            get {
                return ResourceManager.GetString("Login_UserName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username .
        /// </summary>
        public static string Login_UserName_Placeholder {
            get {
                return ResourceManager.GetString("Login_UserName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Logout_Button {
            get {
                return ResourceManager.GetString("Logout_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string Logout_Confirm_Message {
            get {
                return ResourceManager.GetString("Logout_Confirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Logout.
        /// </summary>
        public static string Logout_Confirm_Title {
            get {
                return ResourceManager.GetString("Logout_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank ID.
        /// </summary>
        public static string Maint_BankId_Label {
            get {
                return ResourceManager.GetString("Maint_BankId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., 5.
        /// </summary>
        public static string Maint_BankId_Placeholder {
            get {
                return ResourceManager.GetString("Maint_BankId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank ID must be a positive number.
        /// </summary>
        public static string Maint_BankId_Range {
            get {
                return ResourceManager.GetString("Maint_BankId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank ID is required.
        /// </summary>
        public static string Maint_BankId_Required {
            get {
                return ResourceManager.GetString("Maint_BankId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create / Reset User.
        /// </summary>
        public static string Maint_CreateReset_Button {
            get {
                return ResourceManager.GetString("Maint_CreateReset_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create / Reset Bank User.
        /// </summary>
        public static string Maint_CreateReset_Title {
            get {
                return ResourceManager.GetString("Maint_CreateReset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank ID.
        /// </summary>
        public static string Maint_Result_Bank {
            get {
                return ResourceManager.GetString("Maint_Result_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        public static string Maint_Result_Created {
            get {
                return ResourceManager.GetString("Maint_Result_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User will be forced to change the password on first login..
        /// </summary>
        public static string Maint_Result_Note {
            get {
                return ResourceManager.GetString("Maint_Result_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time password.
        /// </summary>
        public static string Maint_Result_Password {
            get {
                return ResourceManager.GetString("Maint_Result_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully..
        /// </summary>
        public static string Maint_Result_Reset {
            get {
                return ResourceManager.GetString("Maint_Result_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Maint_Result_User {
            get {
                return ResourceManager.GetString("Maint_Result_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Maint_UserName_Label {
            get {
                return ResourceManager.GetString("Maint_UserName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., john.doe.
        /// </summary>
        public static string Maint_UserName_Placeholder {
            get {
                return ResourceManager.GetString("Maint_UserName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 100 characters..
        /// </summary>
        public static string MaxLength_100 {
            get {
                return ResourceManager.GetString("MaxLength_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Tickets per day.
        /// </summary>
        public static string MaxTickets_Label {
            get {
                return ResourceManager.GetString("MaxTickets_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More_Button {
            get {
                return ResourceManager.GetString("More_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Arabic characters allowed.
        /// </summary>
        public static string NameArabic_Invalid {
            get {
                return ResourceManager.GetString("NameArabic_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        public static string NameArabic_Label {
            get {
                return ResourceManager.GetString("NameArabic_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name (Arabic) has a max limit of a (100) characters.
        /// </summary>
        public static string NameArabic_MaxLimit {
            get {
                return ResourceManager.GetString("NameArabic_MaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic) is required.
        /// </summary>
        public static string NameArabic_Required {
            get {
                return ResourceManager.GetString("NameArabic_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only English characters allowed.
        /// </summary>
        public static string NameEnglish_Invalid {
            get {
                return ResourceManager.GetString("NameEnglish_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string NameEnglish_Label {
            get {
                return ResourceManager.GetString("NameEnglish_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name (English) has a max limit of a (100) characters.
        /// </summary>
        public static string NameEnglish_MaxLimit {
            get {
                return ResourceManager.GetString("NameEnglish_MaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English) is required.
        /// </summary>
        public static string NameEnglish_Required {
            get {
                return ResourceManager.GetString("NameEnglish_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services allocated.
        /// </summary>
        public static string No_Services_Allocated {
            get {
                return ResourceManager.GetString("No_Services_Allocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string Password_Min_Length {
            get {
                return ResourceManager.GetString("Password_Min_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation do not match..
        /// </summary>
        public static string Passwords_Must_Match {
            get {
                return ResourceManager.GetString("Passwords_Must_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Changes.
        /// </summary>
        public static string Refresh_Button {
            get {
                return ResourceManager.GetString("Refresh_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload changes.
        /// </summary>
        public static string Reload_Changes {
            get {
                return ResourceManager.GetString("Reload_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Button {
            get {
                return ResourceManager.GetString("Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Search_Name_Label {
            get {
                return ResourceManager.GetString("Search_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name (AR/EN).
        /// </summary>
        public static string Search_Name_Placeholder {
            get {
                return ResourceManager.GetString("Search_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string Select_Button {
            get {
                return ResourceManager.GetString("Select_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        public static string Select_Type_Placeholder {
            get {
                return ResourceManager.GetString("Select_Type_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Services.
        /// </summary>
        public static string Selected_Service_Index_Title {
            get {
                return ResourceManager.GetString("Selected_Service_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service already deleted by another user (Refreshing changes).
        /// </summary>
        public static string Service_Already_Deleted {
            get {
                return ResourceManager.GetString("Service_Already_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service has been modified by another user.
        /// </summary>
        public static string Service_Concurrency_Error {
            get {
                return ResourceManager.GetString("Service_Concurrency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Service.
        /// </summary>
        public static string Service_Create_Button {
            get {
                return ResourceManager.GetString("Service_Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Service.
        /// </summary>
        public static string Service_Create_Title {
            get {
                return ResourceManager.GetString("Service_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Created Successfully.
        /// </summary>
        public static string Service_Created_Successfully {
            get {
                return ResourceManager.GetString("Service_Created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service has been modified by another user. Are you sure you want to delete it?.
        /// </summary>
        public static string Service_Delete_Concurrency_Error {
            get {
                return ResourceManager.GetString("Service_Delete_Concurrency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Deleted Successfully.
        /// </summary>
        public static string Service_Deleted_Successfully {
            get {
                return ResourceManager.GetString("Service_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        public static string Service_Edit_Title {
            get {
                return ResourceManager.GetString("Service_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Service_Index_Title {
            get {
                return ResourceManager.GetString("Service_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter service name (AR).
        /// </summary>
        public static string Service_NameArabic_Placeholder {
            get {
                return ResourceManager.GetString("Service_NameArabic_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter service name (EN).
        /// </summary>
        public static string Service_NameEnglish_Placeholder {
            get {
                return ResourceManager.GetString("Service_NameEnglish_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes detected to service.
        /// </summary>
        public static string Service_NoChangesDetected {
            get {
                return ResourceManager.GetString("Service_NoChangesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found..
        /// </summary>
        public static string Service_Not_Found {
            get {
                return ResourceManager.GetString("Service_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets range should be between (1-100).
        /// </summary>
        public static string Service_Tickets_Range {
            get {
                return ResourceManager.GetString("Service_Tickets_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Updated Successfully.
        /// </summary>
        public static string Service_Updated_Successfully {
            get {
                return ResourceManager.GetString("Service_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update_Button {
            get {
                return ResourceManager.GetString("Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UserName_Required {
            get {
                return ResourceManager.GetString("UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Counters.
        /// </summary>
        public static string View_Counters_Button {
            get {
                return ResourceManager.GetString("View_Counters_Button", resourceCulture);
            }
        }
    }
}
